Update Exercise_2_Multistage_Dockerfiles.md
fix 

 => ERROR [builder 5/5] RUN go build echo-server.go                                                                                                           0.1s
------                                                                                                                                                             
 > [builder 5/5] RUN go build echo-server.go:
0.124 go: go.mod requires go >= 1.24.5 (running go 1.23.12; GOTOOLCHAIN=local)
------
Dockerfile:8
--------------------
   6 |     WORKDIR /go/src
   7 |     
   8 | >>> RUN go build echo-server.go
   9 |     
  10 |     FROM alpine:latest
--------------------
ERROR: failed to solve: process "/bin/sh -c go build echo-server.go" did not complete successfully: exit code: 1